[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "KubeZen"
version = "0.1.0"
description = "A Kubernetes CLI tool"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
authors = [
  {name = "Your Name", email = "you@example.com"},
]
dependencies = [
    "click",
    "libtmux",
]

[project.scripts]
kubezen = "KubeZen.cli:cli" 