[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "KubeZen"
version = "0.0.1"
dependencies = [
    "click",
    "textual",
    "libtmux",
    "kubernetes",
    "kubernetes-asyncio",
    "yappi",
]

[project.scripts]
kubezen = "KubeZen.main:main"
