name: Build KubeZen

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create staging directories
        run: |
          mkdir -p ${{ github.workspace }}/bin
          mkdir -p ${{ github.workspace }}/vim_static_build
          mkdir -p ${{ github.workspace }}/assets/fzf_vim_plugin

      - name: Download kubectl
        run: |
          cd ${{ github.workspace }}
          ./assets/download_scripts/download_kubectl.sh

      - name: Download FZF suite
        run: |
          cd ${{ github.workspace }}
          ./assets/download_scripts/download_fzf_suite.sh

      - name: Build static tmux
        run: |
          cd ${{ github.workspace }}
          ./assets/build_scripts/build_static_tmux.sh 3.3a

      - name: Build static vim
        run: |
          cd ${{ github.workspace }}
          ./assets/build_scripts/build_static_vim.sh v9.1.1415

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pyinstaller
          pip install -e .

      - name: Build with PyInstaller
        run: |
          cd ${{ github.workspace }}
          pyinstaller KubeZen.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: kubezen
          path: ${{ github.workspace }}/dist/kubezen/
          if-no-files-found: error 