name: Build KubeZen Executable

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Or your desired Python version

      - name: Create staging directories for assets
        run: |
          mkdir -p $GITHUB_WORKSPACE/staging_assets/bin
          mkdir -p $GITHUB_WORKSPACE/staging_assets/assets_src/fzf_vim_plugin
          mkdir -p $GITHUB_WORKSPACE/KubeZen/bin # For KubeZen.spec
          mkdir -p $GITHUB_WORKSPACE/KubeZen/assets/fzf_vim_plugin/plugin # For KubeZen.spec
          mkdir -p $GITHUB_WORKSPACE/KubeZen/assets/fzf_vim_plugin/fzf    # For KubeZen.spec
        working-directory: $GITHUB_WORKSPACE

      - name: Download kubectl
        run: bash $GITHUB_WORKSPACE/KubeZen/assets/download_scripts/download_kubectl.sh $GITHUB_WORKSPACE/staging_assets
        working-directory: $GITHUB_WORKSPACE/KubeZen/assets/download_scripts

      - name: Download fzf suite (binary, vim plugin parts, fzf-tmux)
        run: bash $GITHUB_WORKSPACE/KubeZen/assets/download_scripts/download_fzf_suite.sh $GITHUB_WORKSPACE/staging_assets
        working-directory: $GITHUB_WORKSPACE/KubeZen/assets/download_scripts

      - name: Build static tmux
        run: bash $GITHUB_WORKSPACE/KubeZen/assets/build_scripts/build_static_tmux.sh $GITHUB_WORKSPACE/staging_assets
        working-directory: $GITHUB_WORKSPACE/KubeZen/assets/build_scripts

      - name: Build static vim
        run: bash $GITHUB_WORKSPACE/KubeZen/assets/build_scripts/build_static_vim.sh
        # This script outputs to $PWD/vim_static_build, so it will create $GITHUB_WORKSPACE/KubeZen/vim_static_build
        working-directory: $GITHUB_WORKSPACE/KubeZen

      - name: Populate KubeZen/bin for PyInstaller
        run: |
          echo "Copying binaries to KubeZen/bin/"
          cp $GITHUB_WORKSPACE/staging_assets/bin/kubectl $GITHUB_WORKSPACE/KubeZen/bin/kubectl
          cp $GITHUB_WORKSPACE/staging_assets/bin/fzf $GITHUB_WORKSPACE/KubeZen/bin/fzf
          cp $GITHUB_WORKSPACE/staging_assets/bin/fzf-tmux $GITHUB_WORKSPACE/KubeZen/bin/fzf-tmux
          cp $GITHUB_WORKSPACE/staging_assets/bin/tmux $GITHUB_WORKSPACE/KubeZen/bin/tmux 
          # Vim is already in KubeZen/vim_static_build by its build script
          ls -l $GITHUB_WORKSPACE/KubeZen/bin/
        working-directory: $GITHUB_WORKSPACE

      - name: Populate KubeZen/assets/fzf_vim_plugin for PyInstaller
        run: |
          echo "Copying fzf vim plugin files to KubeZen/assets/fzf_vim_plugin/"
          cp $GITHUB_WORKSPACE/staging_assets/assets_src/fzf_vim_plugin/plugin/fzf.vim $GITHUB_WORKSPACE/KubeZen/assets/fzf_vim_plugin/plugin/fzf.vim
          # Copy the entire fzf autoload directory and its contents
          if [ -d "$GITHUB_WORKSPACE/staging_assets/assets_src/fzf_vim_plugin/fzf/autoload" ]; then 
            cp -r $GITHUB_WORKSPACE/staging_assets/assets_src/fzf_vim_plugin/fzf/autoload $GITHUB_WORKSPACE/KubeZen/assets/fzf_vim_plugin/fzf/
          else
            echo "Warning: staging_assets/assets_src/fzf_vim_plugin/fzf/autoload not found"
          fi
          ls -lR $GITHUB_WORKSPACE/KubeZen/assets/fzf_vim_plugin/
        working-directory: $GITHUB_WORKSPACE

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install pyinstaller
        working-directory: $GITHUB_WORKSPACE/KubeZen

      - name: Run PyInstaller
        run: pyinstaller KubeZen.spec
        working-directory: $GITHUB_WORKSPACE/KubeZen

      - name: List output directory
        run: ls -lR $GITHUB_WORKSPACE/KubeZen/dist/
        working-directory: $GITHUB_WORKSPACE

      - name: Upload KubeZen artifact
        uses: actions/upload-artifact@v4
        with:
          name: KubeZen-executable
          path: $GITHUB_WORKSPACE/KubeZen/dist/kubezen # Or KubeZen/dist/ if you want the whole dir 